### PR TITLE
Added EECS data from NOAA in param.py

### LINKED ISSUE #1: Main
Main thread to keep track of todos.

The main thing : the code works but right now it would be hard to loop through multiple parameters at the same time.
Trying to separate the main function to calculate ozone depletion from the parameter definition (now in param.py) and eventually from the plotting stage.

More to come...

### LINKED ISSUE #3: Mass density of sulfate aerosol
Reading this part carefully, this needs to be fixed (line 69)

SO₂ to H2SO4 conversion is not just a matter of injection: overall burden is decided by multiple factors.
For daec, I would use values from the model (i.e. see Fig. 2 here https://gmd.copernicus.org/articles/15/8221/2022/#&gid=1&pid=1)
The values you have now for daec (5*e-13) are,I think, a bit too small.
In general, considering here we're talking about the polar stratosphere, probably the total volume calculated above should also only consider 60S-90S.

### PR DESCRIPTION
**Pull request by dan-visioni**
See issue :)

### CODE REVIEW

**Review by krpetlock — APPROVED** [review]

**Review by krpetlock — APPROVED** [review]

**Review by krpetlock — APPROVED** [review]

**Review by krpetlock — APPROVED** [review]

**Review by krpetlock — APPROVED** [review]

**Review by krpetlock — APPROVED** [review]

**Review by krpetlock — CHANGES_REQUESTED** [review]
Hi Dan, 
I'm not seeing why the k parameter is "noted out" with the # symbol on line 106(new)

**Review by krpetlock — APPROVED** [review]

**Comment by krpetlock** [comment]
-approved the updates, with one comment/request RE: line 106.
I see if I can resolve the branch conflict after my finals tomorrow.  
Kyle

**Comment by dan-visioni** [comment]
Good luck on the finals!
That k is noted out because it's then re-defined in the loop below.

**Review by krpetlock — APPROVED** [review]

**Review by krpetlock — APPROVED** [review]

**Review by krpetlock — APPROVED** [review]

**Review by krpetlock — APPROVED** [review]

**Review by krpetlock — APPROVED** [review]

**Review by krpetlock — APPROVED** [review]

**Review by krpetlock — APPROVED** [review]

**Comment by krpetlock** [comment]
okay

**Review by krpetlock — COMMENTED** [review]
okay

**Review by krpetlock — COMMENTED** [review]
okay

**Pull request closed without merging**
